<a href="https://colab.research.google.com/github/tomonari-masada/course-nlp2020/blob/master/04_PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 04 PyTorch入門（１）
参考資料: 
* PyTorch公式のチュートリアル https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html
* 《20天吃掉那只Pytorch》 https://github.com/lyhue1991/eat_pytorch_in_20_days

注意:
* ランタイムのタイプをGPUにしておいてください。
  * 上のメニュー「ランタイム」→「ランタイムのタイプを変更」で「GPU」を選択 


## 04-01 テンソル

In [39]:
import numpy as np
import torch

### テンソルの作り方

In [40]:
# 1で埋められたテンソルを作る
x = torch.ones(2,5)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [41]:
# 要素のデータ型を確認する
print(x.dtype)

torch.float32


In [42]:
# 0で埋められたテンソルを作る
x = torch.zeros(4,4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [43]:
# 特定の値で埋められたテンソルを作る
x = torch.full((2, 3), 3.141592)
print(x)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


In [44]:
# 不定な値を要素とするテンソルを作る
x = torch.empty(5, 3) 
print(x)

tensor([[-1.2927e+11,  3.0714e-41, -1.3160e+11],
        [ 3.0714e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -1.3293e+11],
        [ 3.0714e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [45]:
# [0,1)の一様乱数を要素とするテンソルを作る
x = torch.rand(5, 3)
print(x)

tensor([[0.3590, 0.5784, 0.9382],
        [0.8041, 0.5007, 0.3232],
        [0.7642, 0.6829, 0.1568],
        [0.9921, 0.6378, 0.6918],
        [0.6599, 0.8316, 0.0901]])


In [46]:
# Pythonのリストからテンソルを作る
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [47]:
# NumPyのndarrayからテンソルを作る
a = np.array([1, 2, 3])
print(a)
t = torch.from_numpy(a)
print(t)
print()

a[0] = -1
print(t)
t[1] = -2
print(a)

[1 2 3]
tensor([1, 2, 3])

tensor([-1,  2,  3])
[-1 -2  3]


In [48]:
# cloneメソッドを使ってテンソルの複製を作る
a = np.array([1, 2, 3])
print(a)
t = torch.from_numpy(a)
print(t)
s = t.clone()
print(s)

s[0] = -1
print(a)
print(s)

a[1] = -2
print(a)
print(s)

[1 2 3]
tensor([1, 2, 3])
tensor([1, 2, 3])
[1 2 3]
tensor([-1,  2,  3])
[ 1 -2  3]
tensor([-1,  2,  3])


In [49]:
# テンソルからndarrayを作る
x = torch.ones(3,4)
print(x)
y = x.numpy()
print(y)
print()

x[0,0] = -1
print(x)
print(y)
print()

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

tensor([[-1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])
[[-1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]



参考: NumPyのnp.copyはshallow copy

cf. https://numpy.org/doc/stable/reference/generated/numpy.copy.html


In [50]:
from copy import deepcopy

x = torch.ones(3,4)
print(x)
y = deepcopy(x.numpy())
x[0,0] = -1
print(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[-1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### テンソルの形状を得る

In [51]:
x = torch.zeros(5, 3) 
print(x)

print(x.size())
print(x.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
torch.Size([5, 3])


### 既存のテンソルから新たにテンソルを作る

In [52]:
# 既存のテンソルから形状を引き継いで新たにテンソルを作る
# 要素のデータ型は変更できる
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 2.0536, -0.5541, -0.7001],
        [ 0.9195,  2.3709, -1.1757],
        [ 0.6505,  0.9588, -0.1387],
        [-0.4290, -3.0167, -0.0701],
        [-1.1674, -0.6669, -0.2206]])


### テンソルの要素のデータ型いろいろ

In [53]:
i = torch.tensor(1)
print(i, i.dtype)

tensor(1) torch.int64


In [54]:
x = torch.tensor(2.0)
print(x, x.dtype)
y = torch.tensor(2.0, dtype=torch.float64)
print(y, y.dtype)
z = torch.tensor(2.0, dtype=torch.float16)
print(z, z.dtype)
print()

print(x + y + z)

tensor(2.) torch.float32
tensor(2., dtype=torch.float64) torch.float64
tensor(2., dtype=torch.float16) torch.float16

tensor(6., dtype=torch.float64)


In [55]:
b = torch.tensor(True)
print(b, b.dtype)

tensor(True) torch.bool


### 特定の型のテンソルとして初期化(1)

In [56]:
i = torch.tensor(1, dtype=torch.int32)
print(i, i.dtype)
x = torch.tensor(2.0, dtype=torch.float)
print(x, x.dtype)
z = torch.tensor(2.0, dtype=torch.double)
print(z, z.dtype)

tensor(1, dtype=torch.int32) torch.int32
tensor(2.) torch.float32
tensor(2., dtype=torch.float64) torch.float64


### 特定の型のテンソルとして初期化(2)

In [57]:
i = torch.IntTensor([1, 2, 3])
print(i, i.dtype)
x = torch.FloatTensor(np.array([2.0, -4.0]))
print(x, x.dtype)
y = torch.DoubleTensor([2.0, -4.0])
print(y, y.dtype)
b = torch.BoolTensor([1, 0, 2, 0])
print(b, b.dtype)

tensor([1, 2, 3], dtype=torch.int32) torch.int32
tensor([ 2., -4.]) torch.float32
tensor([ 2., -4.], dtype=torch.float64) torch.float64
tensor([ True, False,  True, False]) torch.bool


### 要素の型の変更

In [58]:
i = torch.tensor([1, 10])
print(i, i.dtype)
x = i.float()
print(x, x.dtype)
y = i.type(torch.float64)
print(y, y.dtype)
z = i.type_as(x)
print(z, z.dtype)

tensor([ 1, 10]) torch.int64
tensor([ 1., 10.]) torch.float32
tensor([ 1., 10.], dtype=torch.float64) torch.float64
tensor([ 1., 10.]) torch.float32


### スカラーとベクトル

In [59]:
s = torch.tensor(1.0)
print(s)
print(s.dim())
print()
v = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(v)
print(v.dim())
print(v.shape)
print()
v = torch.tensor([4.0])
print(v)
print(v.dim())
print(v.shape)

tensor(1.)
0

tensor([1., 2., 3., 4.])
1
torch.Size([4])

tensor([4.])
1
torch.Size([1])


In [60]:
# 要素がひとつのテンソルから、その要素を単なる数値として取り出す
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1766])
-0.17661455273628235


### 行列

In [61]:
m = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(m)
print(m.dim())
print(m.shape)
print(m[1, 1])

tensor([[1., 2.],
        [3., 4.]])
2
torch.Size([2, 2])
tensor(4.)


### テンソル

In [62]:
t = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
print(t)
print(t.dim())
print(t.shape)
print(t[1, 1, 1])

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
3
torch.Size([2, 2, 2])
tensor(8.)


In [63]:
t = torch.tensor([[[[1.0, 1.0], [2.0, 2.0]], [[3.0, 3.0], [4.0, 4.0]]],
                        [[[5.0, 5.0], [6.0, 6.0]], [[7.0, 7.0], [8.0, 8.0]]]])
print(t)
print(t.dim())
print(t.shape)
print(t[1, 1, 1, 1])

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]]],


        [[[5., 5.],
          [6., 6.]],

         [[7., 7.],
          [8., 8.]]]])
4
torch.Size([2, 2, 2, 2])
tensor(8.)


## 04-02 テンソルのビュー 

### view()メソッド
* viewとreshapeについては、下記リンク先を参照。
 * https://pytorch.org/docs/stable/tensor_view.html

In [64]:
v = torch.arange(0, 12)
print(v)
print(v.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


In [65]:
m34 = v.view(3, 4)
print(m34)
print(m34.shape)

m43 = v.view(4, -1)
print(m43)
print(m43.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([4, 3])


### reshape()メソッド

In [66]:
v = torch.arange(0, 12)
print(v)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [67]:
m26 = v.view(2, 6)
print(m26)
print(m26.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


### contiguousなテンソルとそうでないテンソルの違い
* 「contiguousである」とは、テンソルとしての要素の配置の順番が、メモリ上での要素の配置の順番と一致していることを言う。
* 例えばtメソッドは、見かけ上で転置するだけなので、その結果得られるテンソルでの要素の配置の順番は、メモリ上の要素の配置の順番と一致しなくなる。
* contiguous()メソッドを呼ぶことで、強制的にメモリ上の要素の配置の順番を、テンソルでのそれに一致させることができる。

In [68]:
print(m26.is_contiguous())

m62 = m26.t()
print(m62)
print(m62.is_contiguous())

m62_new = m62.contiguous()
print(m62_new)
print(m62_new.is_contiguous())

True
tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])
False
tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])
True


In [69]:
v = torch.arange(0, 12)
m26 = v.view(2, 6)
m34 = m26.view(3, 4)
print(m34)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [70]:
v = torch.arange(0, 12)
m26 = v.view(2, 6)
m62 = m26.t()
m34 = m62.view(3, 4) # これはエラーになる

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [ ]:
v = torch.arange(0, 12)
m26 = v.view(2, 6)
m62 = m26.t()
m62_new = m62.contiguous()
m34 = m62_new.view(3, 4) # これはエラーにならない
print(m62)
print(m34)

In [ ]:
v = torch.arange(0, 12)
m26 = v.view(2, 6)
m62 = m26.t()
m34 = m62.reshape(3, 4) # reshapeではエラーにならない
print(m62)
print(m34)

### テンソルとその要素のメモリ上での配置
* 下のリンク先が詳しい。
 * https://livebook.manning.com/book/deep-learning-with-pytorch/chapter-3/v-12/198

In [ ]:
m = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
print(m)
print(m.storage())

In [ ]:
m = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
m = m.t()
print(m)
print(m.storage())

## 04-03 テンソルの操作

### 演算

In [ ]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x + y)

In [ ]:
print(torch.add(x, y))

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

### NumPyのndarrayからfrom_numpy()でPyTorchのテンソルを作る

In [ ]:
a = np.zeros(3)
t = torch.from_numpy(a)
print(a)
print(t)

# 元のndarrayを変更するとテンソルも変更されることに注意！
np.add(a, 1, out=a)
print(a)
print(t)

In [ ]:
t = torch.zeros(3)
a = t.numpy()
print(t)
print(a)

t.add_(1)
print(t)
print(a)

### clone()によるテンソルの複製

In [ ]:
t = torch.zeros(3)

a = t.clone().numpy()
print(t)
print(a)

t.add_(1) # aは変わらない
print(t)
print(a)

### インデクシング
* NumPyと同じ。

In [ ]:
x = torch.rand(5, 3)
print(x)
print(x[:, 1])

### item()とtolist()によるPythonの組み込み型への変換

In [ ]:
s = torch.tensor(1.0)
print(s)
print(type(s))
i = s.item()
print(i)
print(type(i))
print()

t = torch.rand(2,2)
print(t)
print(type(t))
l = t.tolist()
print(l)
print(type(l))

### GPUへテンソルを持っていく
* ランタイムのタイプをGPUへ変更してから下のセルを実行する。

In [ ]:
x = torch.rand(5, 3)

if torch.cuda.is_available():
  device = torch.device("cuda")          # a CUDA device object
  y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
  x = x.to(device)                       # or just use strings ``.to("cuda")``
  z = x + y
  print(z)
  w = z.to("cpu")
  print(w)
  print(w.dtype)
  w = z.to("cpu", torch.double)
  print(w)
  print(w.dtype)

## 04-04 自動微分

### それに関して微分をする変数を作る
* requires_gradをTrueにする

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

In [ ]:
y = x + 2
print(y)

### 計算グラフ

In [ ]:
print(y.grad_fn)

In [ ]:
z = y * y * 4
out = z.mean()

print(z, out)

In [ ]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)
print(b.requires_grad)

### バックプロパゲーションの実行

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 4
print(z)
out = z.mean()
print(out)

out.backward()

### 微分係数

In [ ]:
print(x.grad)

### 計算グラフを作らせない

In [ ]:
x = torch.tensor(3., requires_grad=True)
print(x.requires_grad)
y = x ** 2
print(y.requires_grad)
y.backward()
print(x.grad)
print()

with torch.no_grad():
  y = x ** 2
  print(y.requires_grad)

In [ ]:
x = torch.tensor(3., requires_grad=True)
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y))

In [ ]:
# f(x) = a*x**2 + b*x + cの、x=2におけるxに関する微分係数を求める

x = torch.tensor(2.0, requires_grad=True)
a = torch.tensor(1.0)
b = torch.tensor(-2.0)
c = torch.tensor(1.0)

y = a * x * x + b * x + c

y.backward()
print(x.grad)

### 計算グラフの可視化

In [ ]:
!pip install torchviz

In [ ]:
from torchviz import make_dot

x = torch.tensor([2.0], requires_grad=True)
a = torch.tensor([1.0])
b = torch.tensor([-2.0])
c = torch.tensor([1.0])

y = a * torch.pow(x, 2) + b * x + c
make_dot(y, params={'x':x})

### autograd()を使った高階微分
* 第一引数は微分される関数
* 第二引数はそれに関して微分する変数
* create_graphをTrueにすると計算グラフが作られるので、高階微分を計算できるようになる。

例1. $y = ax^3 + bx^2 + cx + d$を、$x$について微分

In [ ]:
x = torch.tensor(0.0, requires_grad=True)
a = torch.tensor(1.0)
b = torch.tensor(-2.0)
c = torch.tensor(1.0)
d = torch.tensor(5.0)
y = a * torch.pow(x, 3) + b * torch.pow(x, 2) + c * x + d

In [ ]:
dy_dx = torch.autograd.grad(y, x) #単に微分するだけ
print(dy_dx) # 要素が一つだけのtupleになっている
print(dy_dx[0].data)

例2. $y=x_1 x_2$を、$x_1$と$x_2$それぞれについて偏微分

In [ ]:
x1 = torch.tensor(0.0, requires_grad=True)
x2 = torch.tensor(0.0, requires_grad=True)
y = x1 * x2

In [ ]:
dy_dx = torch.autograd.grad(y, (x1, x2)) # 単に微分するだけ
print(dy_dx)

例3. $y = ax^3 + bx^2 + cx + d$を、$x$について微分し、さらにそれを微分する

In [ ]:
x = torch.tensor(0.0, requires_grad=True)
a = torch.tensor(1.0)
b = torch.tensor(-2.0)
c = torch.tensor(1.0)
d = torch.tensor(5.0)
y = a * torch.pow(x, 3) + b * torch.pow(x, 2) + c * x + d

In [ ]:
# backpropagationの計算の計算グラフを作らせる
dy_dx = torch.autograd.grad(y, x, create_graph=True) 
print(dy_dx)
print(dy_dx[0].data)

# その計算グラフが表す関数をxで微分
d２y_dx2 = torch.autograd.grad(dy_dx, x)
print(d2y_dx2)
print(d2y_dx2[0].data)

### 多変数関数の偏微分とヘシアン

例. $y=(x_1+3x_2)^2$のヘシアンを求める

In [ ]:
def func(x1, x2):
  return (x1 + 3 * x2) ** 2

x1 = torch.tensor(1.0, requires_grad=True)
x2 = torch.tensor(2.0, requires_grad=True)
y = func(x1, x2)

In [ ]:
# import torch.nn.functional

In [ ]:
pip install --upgrade torch

In [ ]:
import torch

In [ ]:
print(torch.__version__)

In [ ]:

dy_dx1, dy_dx2 = torch.autograd.grad(y, [x1, x2], create_graph=True)
print(dy_dx1.data, dy_dx2.data)
d2y_dx1dx1, d2y_dx1dx2 = torch.autograd.grad(dy_dx1, [x1, x2], retain_graph=True)
print(d2y_dx1dx1.data, d2y_dx1dx2.data)
d2y_dx2dx1, d2y_dx2dx2 = torch.autograd.grad(dy_dx2, [x1, x2])
print(d2y_dx2dx1.data, d2y_dx2dx2.data)

print(torch.autograd.functional.hessian(func, inputs=(x1, x2)))
# print(torch.autograd.function.hessian(func, inputs=(x1, x2)))

## 04-05 自動微分を使った制約なし最適化

例. $f(x)=x^2-2x+1$を最小にする$x$を求める

In [71]:
# 関数の定義
def f(x, a=1.0, b=-2.0, c=1.0):
  return a * torch.pow(x, 2) + b * x + c

In [72]:
# テンソルの準備
x = torch.tensor(10.0, requires_grad=True)

# 最適化手法のインスタンスを作る
#   param: どの変数で微分するか
#   lr: 学習率
optimizer = torch.optim.SGD(params=[x], lr=0.1)

In [73]:
for i in range(1, 101):
  optimizer.zero_grad()
  y = f(x)
  y.backward()
  optimizer.step()
  if i % 5 == 0:
    print(f'iter {i} : f(x) = {y.data:.6f}, x = {x.data:.6f}')

iter 5 : f(x) = 13.589545, x = 3.949120
iter 10 : f(x) = 1.459167, x = 1.966368
iter 15 : f(x) = 0.156677, x = 1.316659
iter 20 : f(x) = 0.016823, x = 1.103763
iter 25 : f(x) = 0.001806, x = 1.034001
iter 30 : f(x) = 0.000194, x = 1.011142
iter 35 : f(x) = 0.000021, x = 1.003651
iter 40 : f(x) = 0.000002, x = 1.001196
iter 45 : f(x) = 0.000000, x = 1.000392
iter 50 : f(x) = 0.000000, x = 1.000128
iter 55 : f(x) = 0.000000, x = 1.000042
iter 60 : f(x) = 0.000000, x = 1.000014
iter 65 : f(x) = 0.000000, x = 1.000005
iter 70 : f(x) = 0.000000, x = 1.000001
iter 75 : f(x) = 0.000000, x = 1.000000
iter 80 : f(x) = 0.000000, x = 1.000000
iter 85 : f(x) = 0.000000, x = 1.000000
iter 90 : f(x) = 0.000000, x = 1.000000
iter 95 : f(x) = 0.000000, x = 1.000000
iter 100 : f(x) = 0.000000, x = 1.000000


# 課題4
* 関数$f(x_1,x_2)=x_1^2+x_2^2$の最小値と、$f(x_1,x_2)$がその最小値をとるときの$x_1$と$x_2$の値を、PyTorchの自動微分を使って求めよう。

In [74]:
# 関数の定義
def f(x1, x2, a=1.0, b=1.0):
  return a * torch.pow(x1, 2) + b * torch.pow(x2,2)

In [79]:
# テンソルの準備
x1 = torch.tensor(10.0, requires_grad=True)
x2 = torch.tensor(10.0, requires_grad=True)

# 最適化手法のインスタンスを作る
#   param: どの変数で微分するか
#   lr: 学習率
optimizer = torch.optim.SGD(params=[x1, x2], lr=0.1)

In [80]:
for i in range(1, 101):
  optimizer.zero_grad()
  y = f(x1,x2)
  y.backward()
  optimizer.step()
  if i % 5 == 0:
    print(f'iter {i} : f(x) = {y.data:.6f}, x1 = {x1.data:.6f}, x2 = {x2.data:.6f}')

iter 5 : f(x) = 33.554428, x1 = 3.276800, x2 = 3.276800
iter 10 : f(x) = 3.602879, x1 = 1.073742, x2 = 1.073742
iter 15 : f(x) = 0.386856, x1 = 0.351844, x2 = 0.351844
iter 20 : f(x) = 0.041538, x1 = 0.115292, x2 = 0.115292
iter 25 : f(x) = 0.004460, x1 = 0.037779, x2 = 0.037779
iter 30 : f(x) = 0.000479, x1 = 0.012379, x2 = 0.012379
iter 35 : f(x) = 0.000051, x1 = 0.004056, x2 = 0.004056
iter 40 : f(x) = 0.000006, x1 = 0.001329, x2 = 0.001329
iter 45 : f(x) = 0.000001, x1 = 0.000436, x2 = 0.000436
iter 50 : f(x) = 0.000000, x1 = 0.000143, x2 = 0.000143
iter 55 : f(x) = 0.000000, x1 = 0.000047, x2 = 0.000047
iter 60 : f(x) = 0.000000, x1 = 0.000015, x2 = 0.000015
iter 65 : f(x) = 0.000000, x1 = 0.000005, x2 = 0.000005
iter 70 : f(x) = 0.000000, x1 = 0.000002, x2 = 0.000002
iter 75 : f(x) = 0.000000, x1 = 0.000001, x2 = 0.000001
iter 80 : f(x) = 0.000000, x1 = 0.000000, x2 = 0.000000
iter 85 : f(x) = 0.000000, x1 = 0.000000, x2 = 0.000000
iter 90 : f(x) = 0.000000, x1 = 0.000000, x2 = 0